name: Update Documentation

on:
  push:
    branches: [documentation-update]
    paths:
      - '**/*.lua'  # Only trigger on Lua file changes
  workflow_dispatch:  # Allow manual triggering

env:
  PYTHON_VERSION: '3.10'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout jo_libs
        uses: actions/checkout@v3
        with:
          path: jo_libs
          fetch-depth: 0
          
      - name: Checkout jo_libs_autodoc
        uses: actions/checkout@v3
        with:
          repository: JOBrice/jo_libs_autodoc
          path: jo_libs_autodoc
          ref: main
          
      - name: Checkout Documentation
        uses: actions/checkout@v3
        with:
          repository: Jump-On-Studios/Documentation
          path: Documentation
          ref: autodoc-integration
          

      - name: Create folders.json
        run: |
          cat > jo_libs_autodoc/folders.json << 'EOF'
          {
            "jo_libs_modules_directory_path": "../jo_libs/jo_libs/modules",
            "vitepress_modules_directory_path": "../Documentation/docs/jo_libs/modules"
          }
          EOF


      # Add this step to see the created folders
      - name: List created folders
        run: |
          echo "Root directory:"
          ls -la
          
          echo "\nContent of jo_libs:"
          ls -la jo_libs
          
          echo "\nContent of jo_libs_autodoc:"
          ls -la jo_libs_autodoc
          
          echo "\nContent of Documentation:"
          ls -la Documentation


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      

      - name: Run documentation generator
        run: |
          cd jo_libs_autodoc
          python generate_vitepress_docs.py

      - name: Run missing examples report
        run: |
          cd jo_libs_autodoc
          python check_missing_examples.py